# Generated by Django 4.2.13 on 2024-08-22 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=100, unique=True)),
                ('element_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_code', models.CharField(max_length=100, unique=True)),
                ('menu_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.ManyToManyField(to='menu_app.element')),
                ('menu_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu_app.menumaster')),
            ],
        ),
    ]
